apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapp
  labels:
    app: notesapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notesapp
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
        - name: notesapp
          image: basiratsk/notesapp
          ports:
            - containerPort: 80 
            ------------
            
            
apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  labels:
    app: notesapp
spec:
  type: NodePort
  selector:
    app: notesapp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000

